<?php
/**
 * Evolvcode CMS - Google reCAPTCHA v3 Validation
 */

class Recaptcha {
    private static $verifyUrl = 'https://www.google.com/recaptcha/api/siteverify';

    /**
     * Verify the reCAPTCHA token
     * 
     * @param string $token The token generated by the frontend
     * @return bool|string True if valid and score is high enough, error message string otherwise
     */
    public static function verify($token) {
        $secretKey = getSetting('recaptcha_secret_key');
        
        // If no secret key is configured, we assume reCAPTCHA is disabled or not set up
        // In a strict environment, you might want to return false here
        if (empty($secretKey)) {
            return true; 
        }

        if (empty($token)) {
            return 'Security token is missing.';
        }

        $data = [
            'secret' => $secretKey,
            'response' => $token,
            'remoteip' => Security::getClientIP()
        ];

        $options = [
            'http' => [
                'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                'method'  => 'POST',
                'content' => http_build_query($data)
            ]
        ];

        $context  = stream_context_create($options);
        $result = @file_get_contents(self::$verifyUrl, false, $context);

        if ($result === false) {
            return 'Failed to connect to reCAPTCHA verification server.';
        }

        $response = json_decode($result);

        if ($response && isset($response->success) && $response->success) {
            // Check score (0.0 to 1.0)
            // 0.5 is a good default threshold
            if (isset($response->score) && $response->score >= 0.5) {
                return true;
            } else {
                return 'Security check failed. Low trust score.';
            }
        } 

        return 'Security check failed. Invalid token.';
    }
}
